<a href="https://colab.research.google.com/github/muneerpalikkal/MyTectraJuly/blob/master/assisgment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [4]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print(z.shape,z.ndim,z.dtype)

(3, 3) 2 int64


In [8]:
print(z.sum(),z.mean())

36 4.0


In [9]:
x=np.zeros_like(z)
y=np.ones_like(z)
print(x)
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
np.power(z,3)

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]])

In [11]:
a=z.T
print(z*a)


[[ 0  3 12]
 [ 3 16 35]
 [12 35 64]]


In [0]:
part b

In [0]:
import numpy as np
import pandas as pd