<a href="https://colab.research.google.com/github/dipbanik/MyTectraJuly/blob/develop/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 
* Numpy is a python library for numeric processing
  * Efficient way to deal with arrays and matrices
  * Allows operation on entire arrays, matrices
* Implemented in C and uses optimized math instructions for speed
* Pandas is built on top of Numpy. 
  * Pandas objects usually accept Numpy arrays
* Resources
  * https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
  
  

## Example

```python
import numpy as np
x = [1, 2, 3]
dx = [ 2 * x for x in x]
print(dx)

# Same operation in numpy
npx = np.array(x) # First convert x into numeric array
dx  = 2 * npx  # Note lack of list comprehension
print(dx)
```

In [1]:
import numpy as np

x = [1, 2, 3]
dx = []
for item in x:
    dx.append(2 * item)
    

print(dx)
print(type(dx))




[2, 4, 6]
<class 'list'>


In [2]:
dx = [ (2 * elem)  for elem in x]
dx

[2, 4, 6]

In [6]:
# Same operation in numpydx = [ 2 * elem for elem in x]
npx = np.array(x) # First convert x into numeric array
type(npx), type(x)


dx = 2 * np.array([10]) + 100 
type(dx)

dx.shape[0]

(numpy.ndarray, list)

In [0]:
x = np.array(range(100))
index = np.array(range(10)) * 2 

x[index]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# NDArray
* ndarray (n-dimensional array) is the primary data structure in NumPy
* elements are all of the same type
* supports multiple numeric types
  * np.float32
  * np.int32
  * np.complex64 etc.
* Unlike python lists, numpy arrays have attributes
  * ndim - number of dimensions
  * shape - shape of the array
  * size - total elements
  * dtype - data type of the elements
* supports operators
* allows fast indexing, slicing and reshaping

In [0]:
# Example
matrix = [
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]
]
arr = np.array(matrix)

print("Shape")
print(arr.shape)

print("Dimensions")
arr.ndim

Shape
(3, 5)
Dimensions


2

In [0]:
x = np.array([30, 200, 200])
x.dtype

dtype('int32')

## Creating Numpy arrays

* There are many ways to create numpy arrays
  * from python lists
  ```python
    arr = np.array([1, 2, 3])
  ```
  * using initialization functions
  ```python
    # Create a 3x4 matrix
    arr = np.zeros((3,4))
    # Create an array same shape as arr, but with 0 elements
    zarr = np.zeros_like(arr)
    # Create an array with ones
    np.ones((2,3))
    # Create an unitialized array
    np.empty((2,3))
  ```
  * using range functions
  ```python
  arr = np.arange(100) #create an array 0..99
  ```

In [0]:
# Create a 3x4 matrix
a = np.zeros((3,4))
# Create an array same shape as arr, but with 0 elements
b = np.zeros_like(a)
# Create an array with ones
c = np.ones((2,3))
# Create an unitialized array
d = np.empty((2,3))
d = d * 0
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.arange(100).reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [13]:
np.arange(100).reshape(5,20).T

array([[ 0, 20, 40, 60, 80],
       [ 1, 21, 41, 61, 81],
       [ 2, 22, 42, 62, 82],
       [ 3, 23, 43, 63, 83],
       [ 4, 24, 44, 64, 84],
       [ 5, 25, 45, 65, 85],
       [ 6, 26, 46, 66, 86],
       [ 7, 27, 47, 67, 87],
       [ 8, 28, 48, 68, 88],
       [ 9, 29, 49, 69, 89],
       [10, 30, 50, 70, 90],
       [11, 31, 51, 71, 91],
       [12, 32, 52, 72, 92],
       [13, 33, 53, 73, 93],
       [14, 34, 54, 74, 94],
       [15, 35, 55, 75, 95],
       [16, 36, 56, 76, 96],
       [17, 37, 57, 77, 97],
       [18, 38, 58, 78, 98],
       [19, 39, 59, 79, 99]])

In [0]:
# Operators
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])

# Mathematical operators
result = x + y
print(result)
result = x * y
print(result)
result = x - y
print(result)

# Unary
result = x.T # transpose
print(result.shape, result.T.shape)

# Summary functions
result = x.sum()
result = x.mean()
result = x.min()
result = x.max()
result = x.argmax()
result = x.argmin()

[ 6  8 10]
[ 5 12 21]
[-4 -4 -4]
(3,) (3,)


In [0]:
arr = np.arange(10)
gt3 = arr > 3
even = arr % 2 == 0
gt3, even

arr [(arr > 3)  | (arr % 2 == 0)]

array([0, 2, 4, 5, 6, 7, 8, 9])

In [0]:
# Slicing
arr = np.array(range(100)).reshape(20,5)
y = arr[0:2, :]
print(id(y))
print(id(arr[0:2, :]))

2170457454432
2170457454352


In [0]:
# Logical slicing
greater_than_3 = arr > 3
print(greater_than_3)

# Boolean indexing
print(arr[arr > 3])
print(arr[greater_than_3])



[[False False False False  True]
 [ True  True  True  True  True]]
[4 5 6 7 8 9]
[4 5 6 7 8 9]


In [0]:
# You can combine multiple conditions at once
arr[(arr > 3) & (arr %2 == 0)]


array([4, 6, 8])

In [0]:
# Iterating through arrays
arr = np.arange(30).reshape(3, 2, 5)

for row in arr:
    print(row)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]]
