<a href="https://colab.research.google.com/github/dipbanik/MyTectraJuly/blob/develop/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 
* Numpy is a python library for numeric processing
  * Efficient way to deal with arrays and matrices
  * Allows operation on entire arrays, matrices
* Implemented in C and uses optimized math instructions for speed
* Pandas is built on top of Numpy. 
  * Pandas objects usually accept Numpy arrays
* Resources
  * https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
  
  

## Example

```python
import numpy as np
x = [1, 2, 3]
dx = [ 2 * x for x in x]
print(dx)

# Same operation in numpy
npx = np.array(x) # First convert x into numeric array
dx  = 2 * npx  # Note lack of list comprehension
print(dx)
```

In [0]:
import numpy as np

x = [1, 2, 3]
dx = []
for item in x:
    dx.append(2 * item)
    

print(dx)
print(type(dx))




[2, 4, 6]
<class 'list'>


In [0]:
dx = [ (2 * elem)  for elem in x]
dx

[2, 4, 6]

In [0]:
# Same operation in numpydx = [ 2 * elem for elem in x]
npx = np.array(x) # First convert x into numeric array
type(npx), type(x)



(numpy.ndarray, list)

In [0]:

dx = 2 * np.array([10,20]) + 100 
type(dx)


numpy.ndarray

In [0]:
dx

array([120, 140])

In [0]:

dx.shape[0]

2

In [0]:
dx

array([120, 140])

In [0]:
x = np.array(range(100))
index = np.array(range(10)) * 2 

index

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
new_var = x[index]

In [0]:
new_var

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# NDArray
* ndarray (n-dimensional array) is the primary data structure in NumPy
* elements are all of the same type
* supports multiple numeric types
  * np.float32
  * np.int32
  * np.complex64 etc.
* Unlike python lists, numpy arrays have attributes
  * ndim - number of dimensions
  * shape - shape of the array
  * size - total elements
  * dtype - data type of the elements
* supports operators
* allows fast indexing, slicing and reshaping

In [0]:
# Example
matrix = [
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]
]
arr = np.array(matrix)

print("Shape")
print(arr.shape)

print("Dimensions")
arr.ndim

arr.dtype

Shape
(3, 5)
Dimensions


dtype('int64')

In [0]:
x = np.array([30, 200, 200])
x.dtype

dtype('int64')

## Creating Numpy arrays

* There are many ways to create numpy arrays
  * from python lists
  ```python
    arr = np.array([1, 2, 3])
  ```
  * using initialization functions
  ```python
    # Create a 3x4 matrix
    arr = np.zeros((3,4))
    # Create an array same shape as arr, but with 0 elements
    zarr = np.zeros_like(arr)
    # Create an array with ones
    np.ones((2,3))
    # Create an unitialized array
    np.empty((2,3))
  ```
  * using range functions
  ```python
  arr = np.arange(100) #create an array 0..99
  ```

In [0]:
# Create a 3x4 matrix
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
# Create an array same shape as arr, but with 0 elements
b = np.zeros_like(matrix)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [0]:
# Create an array with ones
c = np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
# Create an unitialized array
d = np.empty((2,3))
#d = d * 0
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
np.arange(100).reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [0]:
np.arange(100).reshape(5,20).T

array([[ 0, 20, 40, 60, 80],
       [ 1, 21, 41, 61, 81],
       [ 2, 22, 42, 62, 82],
       [ 3, 23, 43, 63, 83],
       [ 4, 24, 44, 64, 84],
       [ 5, 25, 45, 65, 85],
       [ 6, 26, 46, 66, 86],
       [ 7, 27, 47, 67, 87],
       [ 8, 28, 48, 68, 88],
       [ 9, 29, 49, 69, 89],
       [10, 30, 50, 70, 90],
       [11, 31, 51, 71, 91],
       [12, 32, 52, 72, 92],
       [13, 33, 53, 73, 93],
       [14, 34, 54, 74, 94],
       [15, 35, 55, 75, 95],
       [16, 36, 56, 76, 96],
       [17, 37, 57, 77, 97],
       [18, 38, 58, 78, 98],
       [19, 39, 59, 79, 99]])

In [15]:
import numpy as np
# Operators
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])

# Mathematical operators
result = x + y
print(result)
result = x * y
print(result)
result = x - y
print(result)



[ 6  8 10]
[ 5 12 21]
[-4 -4 -4]


In [16]:
x.T

array([1, 2, 3])

In [18]:
# Unary
print(x.reshape(1,-1))
result = x.reshape(1,-1).T # transpose
print(result)
print(result.shape, result.T.shape)



[[1 2 3]]
[[1]
 [2]
 [3]]
(3, 1) (1, 3)


In [0]:
# Summary functions
result = x.sum()
result

6

In [0]:
result = x.mean()
result

2.0

In [0]:
result = x.min()
result

1

In [0]:
result = x.max()
result

3

In [0]:
result = x.argmax()
result

2

In [0]:
result = x.argmin()
result

0

In [0]:
?np.argmax

In [0]:
arr = np.arange(10)
gt3 = arr > 3
even = arr % 2 == 0
gt3, even



(array([False, False, False, False,  True,  True,  True,  True,  True,
         True]),
 array([ True, False,  True, False,  True, False,  True, False,  True,
        False]))

In [0]:
#gt3 =np.array([False, True, False, False,  True,  True,  True,  True,  True,
        # False])

In [0]:
fgh = arr[gt3]

In [0]:
fgh

array([4, 5, 6, 7, 8, 9])

In [0]:
arr [(arr > 3)  | (arr % 2 == 0)]

array([0, 2, 4, 5, 6, 7, 8, 9])

In [0]:
arr [gt3 | even]

array([0, 2, 4, 5, 6, 7, 8, 9])

In [0]:
# Slicing
arr = np.array(range(100)).reshape(20,5)
y = arr[0:2, :]
print(y)
print(id(y))
print(id(arr[0:2, :]))

[[0 1 2 3 4]
 [5 6 7 8 9]]
139721080449424
139721080448544


In [0]:
# Logical slicing
greater_than_3 = arr > 3
print(greater_than_3)

# Boolean indexing
print(arr[arr > 3])
print(arr[greater_than_3])



[[False False False False  True]
 [ True  True  True  True  True]]
[4 5 6 7 8 9]
[4 5 6 7 8 9]


In [0]:
# You can combine multiple conditions at once
arr[(arr > 3) & (arr %2 == 0)]


array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
       72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [0]:
# Iterating through arrays
arr = np.arange(30).reshape(3, 2, 5)

for row in arr:
    print(row)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]]


In [0]:
pip install pandas

In [0]:
import pandas as pd

In [0]:
?pd.read_csv()

In [0]:
?np.zeros()

In [4]:
np.zeros(shape = (2,3), dtype = np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.ones(shape = (3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
?np.identity(5)

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.full((2,3),45)

array([[45, 45, 45],
       [45, 45, 45]])

In [14]:
np.random.rand()

0.7441485506328667