# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [22]:
!wget -c https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv

--2019-07-30 17:39:26--  https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3858 (3.8K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.77K  --.-KB/s    in 0s      

2019-07-30 17:39:26 (80.6 MB/s) - ‘iris.csv’ saved [3858/3858]



In [0]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [0]:
# GRADED
# 
# (a) Using a for loop, iterate through the list x
# and print an item if its divisible by 2 and less than 6
# (b) Using a for loop, iterate through the dictionary y
# and print a single string of the form "company, ceo"
# e.g. "CEO: Apple, Name: Tim Cook" will be the third entry
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = {
    'Satya Nadella': 'Microsoft',
    'Jeff Bezos': 'Amazon',
    'Tim Cook': 'Apple'
}

In [11]:
# GRADED
# Provided below are functions that are completely defined (add_numbers),
# partially defined (sub_numbers) and not defined (mult_numbers)
# (a) Complete sub_numbers so that it return difference of two numbers
# (b) Write a function called mult_numbers to multiply two numbers

def add_numbers(a, b):
    result = a + b
    return result

def sub_numbers(a, b):
    # Write code to return sum of a and b
    result =  a-b #Replace 0 with your code
    return result

def mult_numbers(a, b):
    result = a*b
    return result
# Uncomment the following when you have done the exercise
#a^2-b^2 = ((a+b)*(a-b))
#e.g 5^2 - 4^2 = (5+4)(5-4) = 9
print(mult_numbers(add_numbers(5,4), sub_numbers(5,4)))
# Should print 9

9


In [12]:
arr=np.random.rand(3,3)
print(arr)     
print("shape:")
new_var1=arr.shape
print(new_var1)
print("Dimension:")
new_var2=arr.ndim
print(new_var2)
print("total number of elements:")
new_var3=arr.size
print(new_var3)
print("data type of each element in an array")
new_var4=arr.dtype
print(new_var4)
print("mean value:")
new_var5=arr.mean()
print(new_var5)
arr1=np.zeros_like(arr, dtype=int)
print(arr1)
arr2=np.ones_like(arr, dtype=int)
print(arr2)
dx=[(elem*elem)for elem in arr]
print(dx)
vector_1=np.array(arr)
vector_2=np.array(arr).T
print("arr:\n",vector_1)
print("transpose of arr:\n",vector_2)
result=np.dot(vector_1,vector_2)
print("resultant matrix:\n",result)
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)

[[0.287261   0.5650776  0.14676607]
 [0.72933868 0.27876224 0.69226594]
 [0.50943915 0.18643626 0.11136394]]
shape:
(3, 3)
Dimension:
2
total number of elements:
9
data type of each element in an array
float64
mean value:
0.38963454166970163
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[array([0.08251888, 0.3193127 , 0.02154028]), array([0.53193491, 0.07770839, 0.47923213]), array([0.25952825, 0.03475848, 0.01240193])]
arr:
 [[0.287261   0.5650776  0.14676607]
 [0.72933868 0.27876224 0.69226594]
 [0.50943915 0.18643626 0.11136394]]
transpose of arr:
 [[0.287261   0.72933868 0.50943915]
 [0.5650776  0.27876224 0.18643626]
 [0.14676607 0.69226594 0.11136394]]
resultant matrix:
 [[0.42337185 0.468634   0.2680374 ]
 [0.468634   1.08887543 0.50061853]
 [0.2680374  0.50061853 0.30668865]]


In [29]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print(df.head(10)) #prints the first 10 rows
print(df.shape)#a
print(df[0:])#b
print(df.iloc[2])#c
print("average of sepal_length values")#f
new_var=(df['sepal_length'])
print(new_var.mean())
print("maximum value in sepal_width")#g
print((df['sepal_width']).max())
print("minimum value of petal_width")#h
print((df['petal_width'].min()))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa
(150, 5)
     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3          